In [1]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression


from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix)

In [2]:
df=pd.read_excel("Wildlife Crime News Database.xlsx",sheet_name="Raw_Articles")

In [3]:
print(df.head(5))

           Date_Collected   Relevance  \
0 2026-01-29 23:07:15.329  ✅ Relevant
1 2026-01-29 23:07:17.090  ✅ Relevant
2 2026-01-29 23:07:19.197  ✅ Relevant
3 2026-01-29 23:07:22.756  ✅ Relevant
4 2026-01-29 23:07:24.629  ✅ Relevant

                                               Title  \
0                                        Google News
1  Palamu Tiger Reserve Seizes 60kg Pangolin Scal...
2  Poaching alarm near Ranthambhore: Seized bones...
3  Woman held with 2 kg pangolin scales in Jharkh...
4  Jamshedpur Forest Officials Eye Kolkata Kingpi...

                                             Snippet  \
0  Elephant found shot dead near India–Bhutan bor...
1  Palamu Tiger Reserve Seizes 60kg Pangolin Scal...
2  Poaching alarm near Ranthambhore: Seized bones...
3  Woman held with 2 kg pangolin scales in Jharkh...
4  Jamshedpur Forest Officials Eye Kolkata Kingpi...

                                                 URL              Source  \
0  https://news.google.com/rss/articles/CBMi7gFBV...         Google News
1  https://news.google.com/rss/articles/CBMi-AFBV...      Times of India
2  https://news.google.com/rss/articles/CBMivAFBV...  The Indian Express
3  https://news.google.com/rss/articles/CBMi3wFBV...  telegraphindia.com
4  https://news.google.com/rss/articles/CBMi4gFBV...      Times of India

   Processed              Search_Keyword Duplicate  Unnamed: 9 Unnamed: 10
0       True        wildlife crime India       NaN         NaN         NaN
1       True        wildlife crime India       NaN         NaN         NaN
2      False              poaching India       NaN         NaN         NaN
3      False  wildlife trafficking India       NaN         NaN         NaN
4       True    wildlife smuggling India       NaN         NaN         NaN

In [4]:
print(df.columns)

Index(['Date_Collected', 'Relevance', 'Title', 'Snippet', 'URL', 'Source',
       'Processed', 'Search_Keyword', 'Duplicate', 'Unnamed: 9',
       'Unnamed: 10'],
      dtype='str')

In [5]:
columns_needed = [
    "Title",
    "Snippet",
    "Relevance"
]

existing_columns = [
    col for col in columns_needed
    if col in df.columns
]

df = df[existing_columns]

print(df.head())

                                               Title  \
0                                        Google News
1  Palamu Tiger Reserve Seizes 60kg Pangolin Scal...
2  Poaching alarm near Ranthambhore: Seized bones...
3  Woman held with 2 kg pangolin scales in Jharkh...
4  Jamshedpur Forest Officials Eye Kolkata Kingpi...

                                             Snippet   Relevance
0  Elephant found shot dead near India–Bhutan bor...  ✅ Relevant
1  Palamu Tiger Reserve Seizes 60kg Pangolin Scal...  ✅ Relevant
2  Poaching alarm near Ranthambhore: Seized bones...  ✅ Relevant
3  Woman held with 2 kg pangolin scales in Jharkh...  ✅ Relevant
4  Jamshedpur Forest Officials Eye Kolkata Kingpi...  ✅ Relevant

In [6]:
df.columns

Index(['Title', 'Snippet', 'Relevance'], dtype='str')

In [7]:
df = df.dropna(subset=["Title"])

print(df.shape)

(1103, 3)

In [8]:
df

,Title,Snippet,Relevance
0,Google News,Elephant found shot dead near India–Bhutan bor...,✅ Relevant
1,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,✅ Relevant
2,Poaching alarm near Ranthambhore: Seized bones...,Poaching alarm near Ranthambhore: Seized bones...,✅ Relevant
3,Woman held with 2 kg pangolin scales in Jharkh...,Woman held with 2 kg pangolin scales in Jharkh...,✅ Relevant
4,Jamshedpur Forest Officials Eye Kolkata Kingpi...,Jamshedpur Forest Officials Eye Kolkata Kingpi...,✅ Relevant
...,...,...,...
1098,சிங்கப்பூரில் வனவிலங்குக் கடத்தல் கும்பல் இல்லை,சிங்கப்பூரில் வனவிலங்குக் கடத்தல் கும்பல் இல்ல...,NaN
1099,ప్రపంచంలో ఎక్కువగా స్మగ్లింగ్ అవుతున్న 10 ప్రా...,ప్రపంచంలో ఎక్కువగా స్మగ్లింగ్ అవుతున్న 10 ప్రా...,NaN
1100,వన్యప్రాణుల జాడకు రోబో… విద్యార్థి ఆశ్రిత్ ప్ర...,వన్యప్రాణుల జాడకు రోబో… విద్యార్థి ఆశ్రిత్ ప్ర...,NaN
1101,ప్రాణం తీసిన మటన్ ముక్క #MahabubabadDistrict #...,ప్రాణం తీసిన మటన్ ముక్క #MahabubabadDistrict #...,NaN
1102,యర్రగొండపాలెంలో కార్డెన్ సర్చ్,యర్రగొండపాలెంలో కార్డెన్ సర్చ్ Lokal Telugu,NaN

In [9]:
df["label"] = ""

In [10]:
# CELL 9
# USE EXISTING RELEVANCE LABELS

for i, row in df.iterrows():

    relevance = str(
        row["Relevance"]
    ).lower()

    if "relevant" in relevance:

        df.at[i, "label"] = "crime"

    elif "irrelevant" in relevance:

        df.at[i, "label"] = "other"

In [12]:
# CELL 10
# AUTO LABEL REMAINING NULL RECORDS

crime_keywords = [

    "poaching",
    "poacher",
    "trafficking",
    "smuggling",
    "ivory",
    "pangolin",
    "tiger",
    "leopard skin",
    "animal skin",
    "wildlife crime",
    "forest officials",
    "illegal trade",
    "seized",
    "arrested",
    "raid",
    "gang",
    "tusks",
    "deer meat",
    "bird trafficking",
    "exotic animals",
    "snake venom"
]

other_keywords = [

    "awareness",
    "seminar",
    "conservation",
    "tourism",
    "documentary",
    "history",
    "workshop",
    "research",
    "policy",
    "funding",
    "school program",
    "wildlife protection",
    "national park tourism"
]

for i, row in df.iterrows():

    if row["label"] != "":

        continue

    text = row["Title"]

    crime_match = any(

        word in text

        for word in crime_keywords
    )

    other_match = any(

        word in text

        for word in other_keywords
    )

    if crime_match:

        df.at[i, "label"] = "crime"

    elif other_match:

        df.at[i, "label"] = "other"

In [13]:
df.head(50)

,Title,Snippet,Relevance,label
0,Google News,Elephant found shot dead near India–Bhutan bor...,✅ Relevant,crime
1,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,✅ Relevant,crime
2,Poaching alarm near Ranthambhore: Seized bones...,Poaching alarm near Ranthambhore: Seized bones...,✅ Relevant,crime
3,Woman held with 2 kg pangolin scales in Jharkh...,Woman held with 2 kg pangolin scales in Jharkh...,✅ Relevant,crime
4,Jamshedpur Forest Officials Eye Kolkata Kingpi...,Jamshedpur Forest Officials Eye Kolkata Kingpi...,✅ Relevant,crime
5,Bengaluru Customs foil wildlife smuggling atte...,Bengaluru Customs foil wildlife smuggling atte...,✅ Relevant,crime
6,Passenger Arrested At Mumbai Airport For Smugg...,Passenger Arrested At Mumbai Airport For Smugg...,✅ Relevant,crime
7,"Jamshedpur Wildlife Smuggling Bust: Parrots, C...","Jamshedpur Wildlife Smuggling Bust: Parrots, C...",✅ Relevant,crime
8,Illegal wildlife trade busted from Crawford Ma...,Illegal wildlife trade busted from Crawford Ma...,✅ Relevant,crime
9,Three arrested for illegal wildlife trade in N...,Three arrested for illegal wildlife trade in N...,✅ Relevant,crime
10,Trophy-hunting syndicate of the rich & influen...,Trophy-hunting syndicate of the rich & influen...,✅ Relevant,crime
11,Azamgarh: FIR Registered Against Man for Hunti...,Azamgarh: FIR Registered Against Man for Hunti...,✅ Relevant,crime
12,Five people arrested in Kolhapur district for ...,Five people arrested in Kolhapur district for ...,✅ Relevant,crime
13,Navi Mumbai: Raigad man held for 'hunting' bar...,Navi Mumbai: Raigad man held for 'hunting' bar...,✅ Relevant,crime
14,25-year-old held with tusks in PTR | Ranchi Ne...,Summary Not Available,✅ Relevant,crime
15,Majuli Police detain 17 over ‘poisoning’ 50 mi...,"Dibrugarh: Majuli Police detained 17 people, i...",✅ Relevant,crime
16,Caught! Stuffed walrus & peacock at Amritsar a...,Summary Not Available,✅ Relevant,crime
17,Surat Cobra Venom Racket Busted | Rs 5.85 Cror...,"Surat cobra venom racket busted, 7 arrested wi...",✅ Relevant,crime
18,"Jamshedpur Wildlife Smuggling Bust: Parrots, C...",The Times of India brings the Latest & Top Bre...,✅ Relevant,crime
19,Wildlife Crime in Odisha: Fake Ivory Racket Bu...,Get in-depth coverage of Odisha — from distric...,✅ Relevant,crime
20,Woman wanted in 2013 Akot tiger poaching case ...,Akot: A joint team of the Melghat Tiger Reserv...,✅ Relevant,crime
21,Lizard part racket slithering through Pb’s pan...,Jalandhar/Chandigarh: Lizard privates are bein...,✅ Relevant,crime
22,Leopard Skin Seizure Odisha: Hunter Arrested -...,Odisha Vigilance&#039;s raid leads to the seiz...,✅ Relevant,crime
23,Title Not Found,Three accused arrested for trafficking in wild...,✅ Relevant,crime
24,Female leopard found dead with four paws missi...,A female leopard was found dead in Satara dist...,✅ Relevant,crime
25,Title Not Found,"Aizawl, Dec 14 (UNI) In a joint operation, the...",✅ Relevant,crime
26,7 poachers arrested in two ops by Nagpur fores...,Nagpur: The Nagpur forest department on Thursd...,✅ Relevant,crime
27,Wildlife Crackdown: Police Seize Leopard Skin ...,Read more about Wildlife Crackdown: Police Sei...,✅ Relevant,crime
28,Tenkasi: Man held for attempt to poach wild an...,MADURAI: A 27-year-old man was arrested by the...,✅ Relevant,crime
29,Three held for hunting spotted deer; weapons s...,TENKASI: Alangulam forest range officials have...,✅ Relevant,crime
30,MP News: Poacher Caught Red-Handed With Burnt ...,Summary Not Available,✅ Relevant,crime
31,Wildlife Smugglers Nabbed With Leopard Skin in...,Four suspected wildlife smugglers were arreste...,✅ Relevant,crime
32,Palghar: 3 Arrested For Attempting To Sell 'Ma...,Summary Not Available,✅ Relevant,crime
33,Title Not Found,Customs at Bengaluru airport intercepts wildli...,✅ Relevant,crime
34,Title Not Found,Elephant calf dies from explosive bait in Sath...,✅ Relevant,crime
35,"GRP, RPF Rescue 400 Trafficked Parrots From Tr...",Nearly 400 wild parrots were rescued from the ...,✅ Relevant,crime
36,"Two leopard skins, sambar antlers seized; six ...","At least six persons, including a father and h...",✅ Relevant,crime
37,Title Not Found,In a significant breakthrough against illegal ...,✅ Relevant,crime
38,Man held for killing blackbuck,Berhampur: Odisha forest department officers o...,✅ Relevant,crime
39,Hyderabad: Police seized 15 kgs of Deer meat; ...,Summary Not Available,✅ Relevant,crime
40,Snakes Slaughtered: Wildlife Crime Sparks Outr...,"In Nuh district, a man allegedly killed 10 sna...",✅ Relevant,crime
41,Three blackbucks found dead with gunshot wound...,"Three blackbucks, including two females and on...",✅ Relevant,crime
42,Alipurduar: Three sentenced for leopard skin...,Alipurduar: In a landmark verdict against wild...,✅ Relevant,crime
43,"Poacher Arrested In Similipal, Wild Pig Meat A...",Baripada: In a significant crackdown on wildli...,✅ Relevant,crime
44,Inquiry flags lack of funds for forensic tests...,Inquiry flags lack of funds for forensic tests...,❌ Irrelevant,crime
45,"Amritsar: Smuggled peacock, walrus trophies ri...","Amritsar: Smuggled peacock, walrus trophies ri...",NaN,
46,Mumbai: Three Kalyan-Dombivli residents caught...,Mumbai: Three Kalyan-Dombivli residents caught...,NaN,crime
47,"Tiger claw seized during census, two nabbed in...","Tiger claw seized during census, two nabbed in...",NaN,crime
48,Forest staff can only probe offences under Wil...,Forest staff can only probe offences under Wil...,NaN,
49,25-year-old held with tusks in PTR,25-year-old held with tusks in PTR Times of I...,NaN,crime

In [14]:
print(

    df["Relevance"]
    .isnull()
    .sum()
)

1058

In [15]:
crime_keywords = [

    "poaching",
    "poacher",
    "trafficking",
    "smuggling",
    "ivory",
    "pangolin",
    "tiger",
    "leopard skin",
    "animal skin",
    "wildlife crime",
    "forest officials",
    "illegal trade",
    "seized",
    "arrested",
    "raid",
    "gang",
    "tusks",
    "deer meat",
    "bird trafficking",
    "exotic animals",
    "snake venom",
    "hunting",
    "rhino horn",
    "wildlife traffickers",
    "elephant tusk"
]

other_keywords = [

    "awareness",
    "seminar",
    "conservation",
    "tourism",
    "documentary",
    "history",
    "workshop",
    "research",
    "policy",
    "funding",
    "school program",
    "wildlife protection",
    "national park tourism",
    "essay",
    "photography",
    "wildlife sanctuary",
    "forest department event"
]

for i, row in df.iterrows():

    if row["label"] != "":

        continue

    text = str(
        row["Title"]
    ).lower()

    crime_score = sum(

        word in text

        for word in crime_keywords
    )

    other_score = sum(

        word in text

        for word in other_keywords
    )

    # -------------------------
    # LABELING
    # -------------------------

    if crime_score >= 1:

        df.at[i, "label"] = "crime"

    elif other_score >= 1:

        df.at[i, "label"] = "other"

    else:

        # UNKNOWN ARTICLES

        df.at[i, "label"] = "other"

In [16]:
df.tail(10)

,Title,Snippet,Relevance,label
1093,দস্যুমুক্ত সুন্দরবন গড়তে টানা অভিযান চলবে: কো...,দস্যুমুক্ত সুন্দরবন গড়তে টানা অভিযান চলবে: কো...,NaN,other
1094,ജഗ്ദൽപൂരിൽ 16 കിലോ ഈനാംപേച്ചി തോടുകൾ പിടികൂടി;...,ജഗ്ദൽപൂരിൽ 16 കിലോ ഈനാംപേച്ചി തോടുകൾ പിടികൂടി;...,NaN,crime
1095,ഛത്തീസ്​ഗഡിൽ ഈനാംപേച്ചിക്കടത്ത്: മൂന്ന് പേർ പി...,ഛത്തീസ്​ഗഡിൽ ഈനാംപേച്ചിക്കടത്ത്: മൂന്ന് പേർ പി...,NaN,other
1096,അമേരിക്ക-ഇറാൻ ചർച്ചകൾ പരാജയം; മധ്യസ്ഥതയ്ക്ക് ത...,അമേരിക്ക-ഇറാൻ ചർച്ചകൾ പരാജയം; മധ്യസ്ഥതയ്ക്ക് ത...,NaN,other
1097,ഛത്തീസ്ഗഢില്‍ വൻ വന്യജീവി വേട്ട: 16 കിലോയിലധിക...,ഛത്തീസ്ഗഢില്‍ വൻ വന്യജീവി വേട്ട: 16 കിലോയിലധിക...,NaN,other
1098,சிங்கப்பூரில் வனவிலங்குக் கடத்தல் கும்பல் இல்லை,சிங்கப்பூரில் வனவிலங்குக் கடத்தல் கும்பல் இல்ல...,NaN,other
1099,ప్రపంచంలో ఎక్కువగా స్మగ్లింగ్ అవుతున్న 10 ప్రా...,ప్రపంచంలో ఎక్కువగా స్మగ్లింగ్ అవుతున్న 10 ప్రా...,NaN,other
1100,వన్యప్రాణుల జాడకు రోబో… విద్యార్థి ఆశ్రిత్ ప్ర...,వన్యప్రాణుల జాడకు రోబో… విద్యార్థి ఆశ్రిత్ ప్ర...,NaN,other
1101,ప్రాణం తీసిన మటన్ ముక్క #MahabubabadDistrict #...,ప్రాణం తీసిన మటన్ ముక్క #MahabubabadDistrict #...,NaN,other
1102,యర్రగొండపాలెంలో కార్డెన్ సర్చ్,యర్రగొండపాలెంలో కార్డెన్ సర్చ్ Lokal Telugu,NaN,other

In [17]:
from deep_translator import (
    GoogleTranslator
)

In [18]:
def translate_text(text):

    try:

        return GoogleTranslator(

            source='auto',

            target='en'

        ).translate(text)

    except:

        return text

In [19]:
from deep_translator import (
    GoogleTranslator
)

import re

In [20]:
def is_english(text):

    return bool(

        re.match(

            r'^[a-zA-Z0-9\s\W]+$',

            str(text)
        )
    )

In [21]:
translated_titles = []

for i, title in enumerate(df["Title"]):

    title = str(title)

    try:

        # -------------------------
        # SKIP ENGLISH
        # -------------------------

        if is_english(title):

            translated_titles.append(
                title
            )

        else:

            translated = GoogleTranslator(

                source='auto',

                target='en'

            ).translate(title)

            translated_titles.append(
                translated
            )

        # -------------------------
        # PROGRESS
        # -------------------------

        if i % 50 == 0:

            print(
                f"Processed {i}"
            )

    except:

        translated_titles.append(
            title
        )

df["translated_title"] = (
    translated_titles
)

Processed 0
Processed 50
Processed 100
Processed 150
Processed 200
Processed 250
Processed 300
Processed 350
Processed 400
Processed 450
Processed 500
Processed 550
Processed 600
Processed 650
Processed 700
Processed 750
Processed 800
Processed 850
Processed 900
Processed 950
Processed 1000
Processed 1050
Processed 1100

In [26]:
df.head(50)

,Title,Snippet,Relevance,label,translated_title
0,Google News,Elephant found shot dead near India–Bhutan bor...,✅ Relevant,crime,Google News
1,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...,✅ Relevant,crime,Palamu Tiger Reserve Seizes 60kg Pangolin Scal...
2,Poaching alarm near Ranthambhore: Seized bones...,Poaching alarm near Ranthambhore: Seized bones...,✅ Relevant,crime,Poaching alarm near Ranthambhore: Seized bones...
3,Woman held with 2 kg pangolin scales in Jharkh...,Woman held with 2 kg pangolin scales in Jharkh...,✅ Relevant,crime,Woman held with 2 kg pangolin scales in Jharkh...
4,Jamshedpur Forest Officials Eye Kolkata Kingpi...,Jamshedpur Forest Officials Eye Kolkata Kingpi...,✅ Relevant,crime,Jamshedpur Forest Officials Eye Kolkata Kingpi...
5,Bengaluru Customs foil wildlife smuggling atte...,Bengaluru Customs foil wildlife smuggling atte...,✅ Relevant,crime,Bengaluru Customs foil wildlife smuggling atte...
6,Passenger Arrested At Mumbai Airport For Smugg...,Passenger Arrested At Mumbai Airport For Smugg...,✅ Relevant,crime,Passenger Arrested At Mumbai Airport For Smugg...
7,"Jamshedpur Wildlife Smuggling Bust: Parrots, C...","Jamshedpur Wildlife Smuggling Bust: Parrots, C...",✅ Relevant,crime,"Jamshedpur Wildlife Smuggling Bust: Parrots, C..."
8,Illegal wildlife trade busted from Crawford Ma...,Illegal wildlife trade busted from Crawford Ma...,✅ Relevant,crime,Illegal wildlife trade busted from Crawford Ma...
9,Three arrested for illegal wildlife trade in N...,Three arrested for illegal wildlife trade in N...,✅ Relevant,crime,Three arrested for illegal wildlife trade in N...
10,Trophy-hunting syndicate of the rich & influen...,Trophy-hunting syndicate of the rich & influen...,✅ Relevant,crime,Trophy-hunting syndicate of the rich & influen...
11,Azamgarh: FIR Registered Against Man for Hunti...,Azamgarh: FIR Registered Against Man for Hunti...,✅ Relevant,crime,Azamgarh: FIR Registered Against Man for Hunti...
12,Five people arrested in Kolhapur district for ...,Five people arrested in Kolhapur district for ...,✅ Relevant,crime,Five people arrested in Kolhapur district for ...
13,Navi Mumbai: Raigad man held for 'hunting' bar...,Navi Mumbai: Raigad man held for 'hunting' bar...,✅ Relevant,crime,Navi Mumbai: Raigad man held for 'hunting' bar...
14,25-year-old held with tusks in PTR | Ranchi Ne...,Summary Not Available,✅ Relevant,crime,25-year-old held with tusks in PTR | Ranchi Ne...
15,Majuli Police detain 17 over ‘poisoning’ 50 mi...,"Dibrugarh: Majuli Police detained 17 people, i...",✅ Relevant,crime,Majuli Police detain 17 over ‘poisoning’ 50 mi...
16,Caught! Stuffed walrus & peacock at Amritsar a...,Summary Not Available,✅ Relevant,crime,Caught! Stuffed walrus & peacock at Amritsar a...
17,Surat Cobra Venom Racket Busted | Rs 5.85 Cror...,"Surat cobra venom racket busted, 7 arrested wi...",✅ Relevant,crime,Surat Cobra Venom Racket Busted | Rs 5.85 Cror...
18,"Jamshedpur Wildlife Smuggling Bust: Parrots, C...",The Times of India brings the Latest & Top Bre...,✅ Relevant,crime,"Jamshedpur Wildlife Smuggling Bust: Parrots, C..."
19,Wildlife Crime in Odisha: Fake Ivory Racket Bu...,Get in-depth coverage of Odisha — from distric...,✅ Relevant,crime,Wildlife Crime in Odisha: Fake Ivory Racket Bu...
20,Woman wanted in 2013 Akot tiger poaching case ...,Akot: A joint team of the Melghat Tiger Reserv...,✅ Relevant,crime,Woman wanted in 2013 Akot tiger poaching case ...
21,Lizard part racket slithering through Pb’s pan...,Jalandhar/Chandigarh: Lizard privates are bein...,✅ Relevant,crime,Lizard part racket slithering through Pb’s pan...
22,Leopard Skin Seizure Odisha: Hunter Arrested -...,Odisha Vigilance&#039;s raid leads to the seiz...,✅ Relevant,crime,Leopard Skin Seizure Odisha: Hunter Arrested -...
23,Title Not Found,Three accused arrested for trafficking in wild...,✅ Relevant,crime,Title Not Found
24,Female leopard found dead with four paws missi...,A female leopard was found dead in Satara dist...,✅ Relevant,crime,Female leopard found dead with four paws missi...
25,Title Not Found,"Aizawl, Dec 14 (UNI) In a joint operation, the...",✅ Relevant,crime,Title Not Found
26,7 poachers arrested in two ops by Nagpur fores...,Nagpur: The Nagpur forest department on Thursd...,✅ Relevant,crime,7 poachers arrested in two ops by Nagpur fores...
27,Wildlife Crackdown: Police Seize Leopard Skin ...,Read more about Wildlife Crackdown: Police Sei...,✅ Relevant,crime,Wildlife Crackdown: Police Seize Leopard Skin ...
28,Tenkasi: Man held for attempt to poach wild an...,MADURAI: A 27-year-old man was arrested by the...,✅ Relevant,crime,Tenkasi: Man held for attempt to poach wild an...
29,Three held for hunting spotted deer; weapons s...,TENKASI: Alangulam forest range officials have...,✅ Relevant,crime,Three held for hunting spotted deer; weapons s...
30,MP News: Poacher Caught Red-Handed With Burnt ...,Summary Not Available,✅ Relevant,crime,MP News: Poacher Caught Red-Handed With Burnt ...
31,Wildlife Smugglers Nabbed With Leopard Skin in...,Four suspected wildlife smugglers were arreste...,✅ Relevant,crime,Wildlife Smugglers Nabbed With Leopard Skin in...
32,Palghar: 3 Arrested For Attempting To Sell 'Ma...,Summary Not Available,✅ Relevant,crime,Palghar: 3 Arrested For Attempting To Sell 'Ma...
33,Title Not Found,Customs at Bengaluru airport intercepts wildli...,✅ Relevant,crime,Title Not Found
34,Title Not Found,Elephant calf dies from explosive bait in Sath...,✅ Relevant,crime,Title Not Found
35,"GRP, RPF Rescue 400 Trafficked Parrots From Tr...",Nearly 400 wild parrots were rescued from the ...,✅ Relevant,crime,"GRP, RPF Rescue 400 Trafficked Parrots From Tr..."
36,"Two leopard skins, sambar antlers seized; six ...","At least six persons, including a father and h...",✅ Relevant,crime,"Two leopard skins, sambar antlers seized; six ..."
37,Title Not Found,In a significant breakthrough against illegal ...,✅ Relevant,crime,Title Not Found
38,Man held for killing blackbuck,Berhampur: Odisha forest department officers o...,✅ Relevant,crime,Man held for killing blackbuck
39,Hyderabad: Police seized 15 kgs of Deer meat; ...,Summary Not Available,✅ Relevant,crime,Hyderabad: Police seized 15 kgs of Deer meat; ...
40,Snakes Slaughtered: Wildlife Crime Sparks Outr...,"In Nuh district, a man allegedly killed 10 sna...",✅ Relevant,crime,Snakes Slaughtered: Wildlife Crime Sparks Outr...
41,Three blackbucks found dead with gunshot wound...,"Three blackbucks, including two females and on...",✅ Relevant,crime,Three blackbucks found dead with gunshot wound...
42,Alipurduar: Three sentenced for leopard skin...,Alipurduar: In a landmark verdict against wild...,✅ Relevant,crime,Alipurduar: Three sentenced for leopard skin...
43,"Poacher Arrested In Similipal, Wild Pig Meat A...",Baripada: In a significant crackdown on wildli...,✅ Relevant,crime,"Poacher Arrested In Similipal, Wild Pig Meat A..."
44,Inquiry flags lack of funds for forensic tests...,Inquiry flags lack of funds for forensic tests...,❌ Irrelevant,crime,Inquiry flags lack of funds for forensic tests...
45,"Amritsar: Smuggled peacock, walrus trophies ri...","Amritsar: Smuggled peacock, walrus trophies ri...",NaN,other,"Amritsar: Smuggled peacock, walrus trophies ri..."
46,Mumbai: Three Kalyan-Dombivli residents caught...,Mumbai: Three Kalyan-Dombivli residents caught...,NaN,crime,Mumbai: Three Kalyan-Dombivli residents caught...
47,"Tiger claw seized during census, two nabbed in...","Tiger claw seized during census, two nabbed in...",NaN,crime,"Tiger claw seized during census, two nabbed in..."
48,Forest staff can only probe offences under Wil...,Forest staff can only probe offences under Wil...,NaN,other,Forest staff can only probe offences under Wil...
49,25-year-old held with tusks in PTR,25-year-old held with tusks in PTR Times of I...,NaN,crime,25-year-old held with tusks in PTR

In [22]:
X = df["translated_title"]

y = df["label"]

In [23]:
X_train, X_test, y_train, y_test = (

    train_test_split(

        X,
        y,

        test_size=0.2,

        random_state=42,

        stratify=y
    )
)

In [24]:
print(len(X_train))
print(len(X_test))

882
221

In [25]:
model = Pipeline([

    (

        "tfidf",

        TfidfVectorizer(

            stop_words="english",

            ngram_range=(1,3),

            max_features=20000,

            min_df=2
        )
    ),

    (

        "clf",

        LogisticRegression(

            max_iter=5000
        )
    )
])

In [26]:
print("TRAINING MODEL...")

model.fit(
    X_train,
    y_train
)

print("MODEL TRAINED")

TRAINING MODEL...
MODEL TRAINED

In [27]:
predictions = model.predict(
    X_test
)

In [28]:
from sklearn.metrics import (

    accuracy_score,

    classification_report
)

accuracy = accuracy_score(

    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 89.14 %

In [29]:
print(

    classification_report(

        y_test,
        predictions
    )
)

              precision    recall  f1-score   support

       crime       0.92      0.80      0.86        91
       other       0.87      0.95      0.91       130

    accuracy                           0.89       221
   macro avg       0.90      0.88      0.89       221
weighted avg       0.89      0.89      0.89       221

In [30]:
import joblib

joblib.dump(

    model,

    "../models/wildlife_crime_model.pkl"
)

print("✅ MODEL SAVED")

✅ MODEL SAVED